"""Added partitioned table

Revision ID: fef1c3e3b78c
Revises: 
Create Date: 2023-06-20 13:13:15.148009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fef1c3e3b78c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partitioned_table",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("peaktemp", sa.Integer(), nullable=True),
        sa.Column("unitsales", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("city_id", "log_date"),
        postgresql_partition_by="RANGE (log_date)",
    )
    op.create_table(
        "partitioned_table_2023",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("peaktemp", sa.Integer(), nullable=True),
        sa.Column("unitsales", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("city_id", "log_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("partitioned_table_2023")
    op.drop_table("partitioned_table")
    # ### end Alembic commands ###
